name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - 'docs/**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: "false"

jobs:
  test:
    name: ${{ matrix.os }} - Julia ${{ matrix.julia_version }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        arch:
          - x64
        julia_version:
          - '1.10'
          - '1.11'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Julia cache
        uses: julia-actions/cache@v2

      - name: Install Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia_version }}
          arch: ${{ matrix.arch }}
          show-versioninfo: true

      - name: Run Julia tests
        uses: julia-actions/julia-runtest@v1
        with:
          coverage: false
        env:
          CATALYST_DEBUG: 1

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session for debugging
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled && always() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
